version: "3.8"

volumes:
  db-data:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/time-api:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/time-front:/app
    ports:
      - "4000:3000"
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: time-db
    volumes:
      - db-data:/var/lib/postgresql/time_db_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
