version: "3.8"

volumes:
  db-data:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/time-api:/app
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - "db"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/time-front:/app
    ports:
      - "4000:3000"

  db:
    image: postgres:14
    container_name: time-db
    volumes:
      - db-data:/var/lib/postgresql/time_db_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: time_db_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

networks:
  local: {}
